# Org3 CA Persistent Volume Override — Full CA Home

networks:
  test:
    name: fabric_test

volumes:
  fabric_ca_org3:
    external: true

services:
  ca_org3:
    volumes:
      - fabric_ca_org3:/etc/hyperledger/fabric-ca-server
